spring:
  profiles:
    active: 
    - dev
    
---  
server:
  port: 8301
  
spring:
  profiles: dev
  application:
    name: application
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
    register-with-eureka: false   
---   
 server:
  port: 8302
  
spring:
  profiles: sit
  application:
    name: application
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
    register-with-eureka: false
