spring:
  profiles:
    active: 
    - dev
---  
server:
 port: 8202 
 
spring:
  profiles: dev
  application:
    name: config-server-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
    register-with-eureka: false   
---      
#server:
 # port: 8201
  
spring:
  profiles: test
  application:
    name: provider-dept
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/study01?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: '{cipher}AQBppS0cn/DkY6peAYCA4Cvk0c9v7hgW3D7Sdflm0Fr/oBiUGV3ahLaUAylhK2FOplXSbtTwPvJ2oezstH3prwq4XaIw8A3x3cf6m/kwHNWcmZ5DZc800aGtsPSJLwL4am6uu8/OMueo0b7zRyA/1MrMDp4bMuZ8Y3DBXdb17Z0zHhwYNnjp2tTbS04tB1Jrwy4BelF5wG3IeMQCJPglLafCm3L+TuGLyTXh31XFK+y/3Kvc/GwatrtV7cyeaDI+1avVXDWzzODjT5sxf+MxN5SaRBPIqfyAkhltT4P0uWE21mboCiH/Fe39yQGI7BuuRGUrUJQa9nzBM6NMDnrr+K83n9QeVjQZ/wiOZXL5K41IDxAZ9AeCh5gNwXoZol1F4n4='
    # Mysql8.0请改为com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #druid连接池配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    # 配置监控统计拦截的filters,去掉监控界面sql无法统计，‘wall’用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    userGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500  
    stream:
      binders: # 在此处配置要绑定的rabbitmq的服务信息；
        defaultRabbit: # 表示定义的名称，用于于binding整合
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: 192.168.184.128
                port: 5672
                username: guest
                password: guest
                virtual-host: /
      bindings: # 服务的整合处理
        output: # 这个名字是一个通道的名称，在分析具体源代码的时候会进行说明
          destination: studyExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为对象json，如果是文本则设置“text/plain”
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
            
#Mybatis配置
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.springcloud.entities
    configuration:
      cache-enabled: true #开启二级缓存
      map-underscore-to-camel-case: true #开启驼峰命名
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
    register-with-eureka: false
